version: "3.9"

services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAMS}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: angular_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
